# Generated by Django 4.0.4 on 2022-05-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('vinculo', models.CharField(max_length=20)),
            ],
        ),
    ]
