# Generated by Django 4.0.4 on 2022-05-13 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='id_uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.uf', verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='id_banco',
            field=models.IntegerField(verbose_name='Id do Banco'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id_cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='id_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.pessoa', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.IntegerField(verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='id_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.conta', verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='id_endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.endereco', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='vinculo',
            field=models.CharField(choices=[('Vinculo 1', 'Vinculo 1'), ('Vinculo 2', 'Vinculo 2')], max_length=20, verbose_name='Vínculo'),
        ),
    ]
