# Generated by Django 4.0.4 on 2022-05-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_cidade_id_uf_alter_conta_id_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='id_banco',
            field=models.IntegerField(verbose_name='ID do Banco'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
    ]
